# Generated by Django 4.2 on 2023-04-11 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='https://i.pinimg.com/originals/b8/7b/94/b87b94048722cfc809bc905823b45909.png', verbose_name='이미지')),
                ('content', models.TextField(verbose_name='내용')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermodel', to='user.usermodel', verbose_name='이름')),
            ],
        ),
    ]
