# Generated by Django 4.2 on 2023-04-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='image',
            field=models.URLField(default='https://i.pinimg.com/originals/b8/7b/94/b87b94048722cfc809bc905823b45909.png', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='tweetmodel',
            table=None,
        ),
    ]
