# Generated by Django 4.2 on 2023-04-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='이름')),
                ('password', models.CharField(max_length=500, verbose_name='비밀번호')),
                ('bio', models.TextField(blank=True, verbose_name='자기소개')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
